import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.sass";

import { CurrencyContext } from "../store/currencyContextStore";
import { QueryProvider } from "../libs/react-query-lib/QueryProvider";
import Title from "../components/common/Title";
import HydratedPosts from "@/libs/react-query-lib/HydrateProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <QueryProvider>
                    <Title />
                    <HydratedPosts>
                        <CurrencyContext>{children}</CurrencyContext>
                    </HydratedPosts>
                </QueryProvider>
            </body>
        </html>
    );
}
